### ISSUE TITLE
Issues While Replicating Results from "Updating" Part of CEPROT

### ISSUE THREAD

**Issue by Ahmadreza-SY** [CEPROTest/CEPROT#1]
Hello,

I am attempting to replicate the "updating" portion of your work to achieve the results reported in your paper. However, I encountered several issues during training, output generation, and evaluation. I have outlined these issues below and would appreciate your guidance on resolving them to ensure accurate replication of your work.

# 1. Configuration Issues
1. In the following location, should the `decoder_path` be `'Salesforce/codet5-base'`?
  https://github.com/CEPROTest/CEPROT/blob/c74bbcf70c5731c607cc09f8c5dc9404032f0e3e/code/updating/codet5/codet5_edit_focal.py#L32

2. In the configuration, there are two versions of files for evaluation: `test.json` and `fpc_infer_data.json`. However, only `test.json` is present in the data branch within the `gen.zip` file. I have two questions here:
  * What is `fpc_infer_data.json`, and is it required to replicate your results?
  * Is it acceptable to set both the dev and test files to `test.json`?
  https://github.com/CEPROTest/CEPROT/blob/c74bbcf70c5731c607cc09f8c5dc9404032f0e3e/code/updating/codet5/codet5_edit_focal.py#L57-L59

3. We added `fpc_` as a prefix to `fpc_test_epoch` output files to make the code work. Please confirm if this is correct:
  https://github.com/CEPROTest/CEPROT/blob/c74bbcf70c5731c607cc09f8c5dc9404032f0e3e/code/updating/codet5/train_codet5_edit_focal.py#L240

4. To run the `updating/codet5/train_codet5_edit_focal.py` without encountering import errors, we needed to copy the `updating/ablation_study/bleu.py` file to `updating/codet5`. We also removed "model." from the imports in the following locations. Please confirm that these fixes are correct:

https://github.com/CEPROTest/CEPROT/blob/c74bbcf70c5731c607cc09f8c5dc9404032f0e3e/code/updating/codet5/train_codet5_edit_focal.py#L9-L11
https://github.com/CEPROTest/CEPROT/blob/c74bbcf70c5731c607cc09f8c5dc9404032f0e3e/code/updating/codet5/train_codet5_edit_focal.py#L19

# 2. Evaluation Issues
- After running your train script, I received `None` for all output files. I noticed that `test_tgt` is explicitly set to `"None"` in two locations. Could you clarify the correct way to fix this? Here are the two locations I am referring to:
  https://github.com/CEPROTest/CEPROT/blob/c74bbcf70c5731c607cc09f8c5dc9404032f0e3e/code/updating/codet5/codet5_edit_focal.py#L118-L124
  https://github.com/CEPROTest/CEPROT/blob/c74bbcf70c5731c607cc09f8c5dc9404032f0e3e/code/updating/codet5/codet5_edit_focal.py#L133-L140

- You mentioned in the following locations that the CodeBLEU score can be computed using the provided scripts. However, I could not find any scripts for this purpose:
  https://github.com/CEPROTest/CEPROT/blob/c74bbcf70c5731c607cc09f8c5dc9404032f0e3e/code/README.md?plain=1#L22-L23
  https://github.com/CEPROTest/CEPROT/blob/c74bbcf70c5731c607cc09f8c5dc9404032f0e3e/README.md?plain=1#L125-L129

Thank you for your assistance.

**Comment by CEPROTest** [comment]
# 1
## 1 
Yes, you can use this.
## 2
Because ours is a two-stage model, the fpc data is obtained through the classification in the first stage. You can see the fpc explanation in the paper.
## 3
I think you shouldn't add these, you should run the classification model first
## 4
Yes. It's correct.

# 2
- You can replace `self.test_tgt = None` with this `self.test_tgt = test_tgt`
- The CodeBLEU, https://github.com/microsoft/CodeXGLUE/blob/main/Code-Code/code-to-code-trans/CodeBLEU.MD
