### ISSUE TITLE
请教一下问题

### ISSUE THREAD

**Issue by BustlingStudpid96** [CEPROTest/CEPROT#2]
在classfier的config.py，44行，dev_filename应该填哪个文件？
在codet5_edit_focal.py，32行，57行，
1、self.decoder_path = 'codet5-base'，还是roberta-base？
2、self.dev_filename，self.train_filename，self.test_filename 应该分别是什么？后两个使用master分支gen压缩包里的吗？
非常感谢！

**Comment by CEPROTest** [comment]
在classfier的config.py，44行，dev_filename应该填哪个文件？
> 这个是分类数据集的validation dataset

在codet5_edit_focal.py，32行，57行，
1、self.decoder_path = 'codet5-base'，还是roberta-base？
> 使用codet5-base

2、self.dev_filename，self.train_filename，self.test_filename 应该分别是什么？后两个使用master分支gen压缩包里的吗？
非常感谢！
> 是的 对于生成更新任务来说，使用gen压缩包里的数据集。分别是validation train test数据集的路径名称。

**Comment by BustlingStudpid96** [comment]
在项目给的数据集里面只有train.json、test.json、train_part.json、test_part.json，没有找到验证集，是要自己划分吗？

**Comment by CEPROTest** [comment]
当时我们的做法是去掉了validation，你看论文中的数据构造，我们没用到validation。
如果单纯复现我们的，可以不用考虑validation，你可以直接finetune，最后测试一下（但是不能把test当validation）。
如果你们有自己的任务，也可以自己重新划分，使用验证集调整参数最后测试。

**Comment by BustlingStudpid96** [comment]
谢谢♪(･ω･)ﾉ
